### ISSUE TITLE
Server Unavailable message

### ISSUE THREAD

**Issue by ellisgl** [WarheadsSE/node-gntp#3]
I'm showing "Server Unavailable" but see data in the console. Is this normal?

**Comment by WarheadsSE** [comment]
Could you please be more specific?
- Are you using it as a client or as a server?
- Could I have a gist of the output?
- Could I have a pertinent link or gist of the code (pieces) ?

**Comment by ellisgl** [comment]
Running the server.js script
Running Growl for Windows and have it subscribe to server. 

Grow for Windows shows the following under Network / Subscribe to notifications from other computers:
test
GNTP 127.0.0.1:23057
server unavailable

**Comment by ellisgl** [comment]
Oh in the node console, I get this:

SERVER RECV:331 on 192
RCVD:331 on 192
good:yes

**Comment by WarheadsSE** [comment]
Ah, yes, this is because the server.js is an example of what is necessary, and has not been fully fleshed out. It is not a complete server at this time.

**Comment by ellisgl** [comment]
Ah! Have any sample code I can play with?

**Comment by WarheadsSE** [comment]
At the moment, I can probably dig something up to upload. The biggest thing is that subscribe & forwarding is not fleshed out, nor are full error handling. I have been trying to sort out a better performing parser in my spare time, which I have not had a lot of recently.

For simply receiving & responding, I have manged to crank > 2000 notifications/sec when on the same test box as the client script.

**Comment by ellisgl** [comment]
Yeah - I was just going to throw out notifications to subscribers when tickets came in for support =)

**Comment by WarheadsSE** [comment]
Then we will need to put in password and client management as well as
subscribe functionality.

**Comment by ellisgl** [comment]
Good plan!

**Comment by WarheadsSE** [comment]
@ellisgl bump

**Comment by ellisgl** [comment]
Wow, ah.. Yeah, 3 years ago I needed this, but now I don't.

**Comment by WarheadsSE** [comment]
I figured I'd knock it and see who might still want this. I haven't really needed to touch this in a looong time.

**Comment by ellisgl** [comment]
Sounds like my repos.. hahah
